version: '3'
services:
  postgres-service:
    image: postgres:latest
    container_name: postgres-container
    ports:
      - 5434:5432/tcp
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER: $DB_USER
#    volumes:
#      - /var/lib/postgres
#      - ./dbscripts/postgres:/docker-entrypoint-initdb.d