version: '3'
services:
  library_management:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 9032:8000
    volumes:
      - ~/library_management/static:/app
volumes:
  library-files: