version: '3'
services:
  library-db:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    restart: always
    volumes:
      - postgres-library-data:/var/lib/postgresql/data/

  library_management:
    build: .
    command: >
      sh -c "python -m manage migrate &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    container_name: library_management
    ports:
      - 9032:8000
    env_file:
      - .env
    depends_on:
      - library-db
    restart: on-failure

volumes:
  postgres-library-data: